services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - api
    networks:
      - app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    expose:
      - "3000"
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - "5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
