services:
  couchbase:
    image: couchbase:latest
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=017985
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - COUCHBASE_HOST=couchbase
      - COUCHBASE_USERNAME=Administrator
      - COUCHBASE_PASSWORD=017985
      - COUCHBASE_BUCKET=doc1
    ports:
      - "3000:3000"
    depends_on:
      - couchbase
    networks:
      - app-network

networks:
  app-network:
    external: false

